### ISSUE TITLE
can not apply run flutter run 

### ISSUE THREAD

**Issue by vikbert** [bizz84/layout-demo-flutter#3]
as I did `flutter run`, I got the following ERROR messages:

```
~/s/f/layout-demo-flutter   master   flutter run
Running "flutter packages get" in layout-demo-flutter...     0.8s
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.                                            0.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

**Comment by xiewei-wayne** [comment]
@vikbert 

Please try running 'pod install' first. 

------------------------------------------------------------------------------------------------

➜  layout-demo-flutter git:(master) ✗ **flutter -v doctor**    
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.5.1 at /Users/xiewei/flutter
    • Framework revision c7ea3ca377 (8 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xiewei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xiewei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • iPhone X • 6EC37B94-C8CB-4433-870D-723D38239608 • ios • iOS 11.4 (simulator)

• No issues found!
➜  layout-demo-flutter git:(master) ✗ **pwd**
/Users/xiewei/demos/layout-demo-flutter
➜  layout-demo-flutter git:(master) ✗ **cd ios** 
➜  ios git:(master) ✗ ls
Flutter                 Podfile                 Runner                  Runner.xcworkspace
Frameworks              Podfile.lock            Runner.xcodeproj        ServiceDefinitions.json
➜  ios git:(master) ✗ **pod install**
Analyzing dependencies
Fetching podspec for `Flutter` from `Pods/.symlinks/flutter/ios`
Downloading dependencies
Using Flutter (1.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
➜  ios git:(master) ✗ **ls**
Flutter                 Podfile                 Pods                    Runner.xcodeproj        ServiceDefinitions.json
Frameworks              Podfile.lock            Runner                  Runner.xcworkspace
➜  ios git:(master) ✗ **ls Frameworks** 
➜  ios git:(master) ✗ **flutter run**
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
➜  ios git:(master) ✗ **pwd**
/Users/xiewei/demos/layout-demo-flutter/ios
➜  ios git:(master) ✗ **cd ..**
➜  layout-demo-flutter git:(master) ✗ **ls**
LICENSE.md                      build                           layout_demo_flutter.iml         pubspec.yaml
README.md                       flutter-stack.sketch            layout_demo_flutter_android.iml screenshots
android                         gen                             lib                             test
assets                          ios                             pubspec.lock
➜  layout-demo-flutter git:(master) ✗ **flutter run**
Launching lib/main.dart on iPhone X in debug mode...
Syncing files to device iPhone X...                          4.8s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

**Comment by vikbert** [comment]
thanks. It works for me. @xiewei-wayne

**Comment by adavis605** [comment]
im having the same issue but I dont understand the answer to fix it

**Comment by adavis605** [comment]
> thanks. It works for me. @xiewei-wayne

can you please explain how you got it to work

**Comment by bizz84** [comment]
I updated the project. Should work now. Closing but feel free to reopen if it's still a problem.
